sudo: required
services:
  - docker
before_install:
  - docker build -t fabis94/docker-react -f Dockerfile.dev .
script:
  - docker run fabis94/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-469333520610"
  bucket_path: "docker-react-test"
  on:
    branch: "master"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
